<?php

$_COS_LANG_MODULE = array ();


$_COS_LANG_MODULE['category_add_title'] = 'Tilføj kategori';
$_COS_LANG_MODULE['category_add_action'] = 'Kategori blev tilføjet';
$_COS_LANG_MODULE['category_add_sub_title'] = 'Tilføj under kategori';
$_COS_LANG_MODULE['category_add_sub_action'] = 'Under kategori blev tilføjet';
$_COS_LANG_MODULE['category_deleted'] = 'Kategori blev slettet';
$_COS_LANG_MODULE['category_edit_title'] = 'Ret kategori';
$_COS_LANG_MODULE['category_edit_action_message'] = 'Kategori blev opdateret';
$_COS_LANG_MODULE['category_form_add_legend'] = 'Tilføj kategori';
$_COS_LANG_MODULE['category_form_add_title'] = 'Titel';
$_COS_LANG_MODULE['category_form_add_submit'] = 'Tilføj';
$_COS_LANG_MODULE['category_form_delete_submit'] = 'Slet';
$_COS_LANG_MODULE['category_form_update_legend'] = 'Opdater kategori';
$_COS_LANG_MODULE['category_form_title'] = 'Tilføj kategori';
$_COS_LANG_MODULE['category_form_update_submit'] = 'Opdater';
$_COS_LANG_MODULE['category_delete_title'] = 'Slet kategori';
$_COS_LANG_MODULE['category_form_delete_legend'] = 'Bekræft slettelse af kategori';
$_COS_LANG_MODULE['category_add_sub'] = 'Tilføj under kategori';
$_COS_LANG_MODULE['category_error_has_children'] = 'Slet først under kategorier';

$_COS_LANG_MODULE['category_form_add_abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['category_form_add_description'] = 'Beskrivelse';
