<?php

$_COS_LANG_MODULE['Add category'] = 'Tilføj kategori';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Description'] = 'Beskrivelse';
$_COS_LANG_MODULE['Add'] = 'Tilføj';
$_COS_LANG_MODULE['Delete category'] = 'Slet kategori';
$_COS_LANG_MODULE['Edit category'] = 'Rediger kategori';
$_COS_LANG_MODULE['Send'] = 'Send';
$_COS_LANG_MODULE['Category has been added'] = 'Kategori er blevet tilføjet';
$_COS_LANG_MODULE['Edit'] = 'Rediger';
$_COS_LANG_MODULE['Delete'] = 'Slet';
$_COS_LANG_MODULE['Add sub category'] = 'Tilføj underkategori';
$_COS_LANG_MODULE['Sub category has been added'] = 'Sub kategori er blevet tilføjet';
$_COS_LANG_MODULE['Category has sub categories'] = 'Kategori har underkategorier';
$_COS_LANG_MODULE['Category has been deleted'] = 'Kategori er blevet slettet';
$_COS_LANG_MODULE['Category has been updated'] = 'Kategori er blevet opdateret';
