<?php

$_COS_LANG_MODULE = array ();


$_COS_LANG_MODULE['category_add_title'] = 'Add category';
$_COS_LANG_MODULE['category_add_action'] = 'Category added';
$_COS_LANG_MODULE['category_add_sub_title'] = 'Add sub category';
$_COS_LANG_MODULE['category_add_sub_action'] = 'Sub category added';
$_COS_LANG_MODULE['category_deleted'] = 'Category deleted';
$_COS_LANG_MODULE['category_edit_title'] = 'Edit category';
$_COS_LANG_MODULE['category_edit_action_message'] = 'Category updated';
$_COS_LANG_MODULE['category_form_add_legend'] = 'Add kategory';
$_COS_LANG_MODULE['category_form_add_title'] = 'Title';
$_COS_LANG_MODULE['category_form_add_submit'] = 'Add';
$_COS_LANG_MODULE['category_form_delete_submit'] = 'Delete';
$_COS_LANG_MODULE['category_form_update_legend'] = 'Update category';
$_COS_LANG_MODULE['category_form_title'] = 'Add category';
$_COS_LANG_MODULE['category_form_update_submit'] = 'Update';
$_COS_LANG_MODULE['category_delete_title'] = 'Delete category';
$_COS_LANG_MODULE['category_form_delete_legend'] = 'Confirm delete category';
$_COS_LANG_MODULE['category_add_sub'] = 'Add sub category';
$_COS_LANG_MODULE['category_error_has_children'] = 'You will need to first delete sub categories';

$_COS_LANG_MODULE['category_form_add_abstract'] = 'Abstract';
$_COS_LANG_MODULE['category_form_add_description'] = 'Description';
