<?php

$_COS_LANG_MODULE['Add category'] = 'Add category';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Abstract'] = 'Abstract';
$_COS_LANG_MODULE['Description'] = 'Description';
$_COS_LANG_MODULE['Add'] = 'Add';
$_COS_LANG_MODULE['Delete category'] = 'Delete category';
$_COS_LANG_MODULE['Edit category'] = 'Edit category';
$_COS_LANG_MODULE['Send'] = 'Send';
$_COS_LANG_MODULE['Category has been added'] = 'Category has been added';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Add sub category'] = 'Add sub category';
$_COS_LANG_MODULE['Sub category has been added'] = 'Sub category has been added';
$_COS_LANG_MODULE['Category has sub categories'] = 'Category has sub categories';
$_COS_LANG_MODULE['Category has been deleted'] = 'Category has been deleted';
$_COS_LANG_MODULE['Category has been updated'] = 'Category has been updated';
