<?php

$_COS_LANG_MODULE['Add category'] = 'Legg til kategori';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Description'] = 'Beskrivelse';
$_COS_LANG_MODULE['Add'] = 'Legg';
$_COS_LANG_MODULE['Delete category'] = 'Klare kategorier';
$_COS_LANG_MODULE['Edit category'] = 'Rediger kategori';
$_COS_LANG_MODULE['Send'] = 'Send';
$_COS_LANG_MODULE['Category has been added'] = 'Seksjoner har blitt lagt';
$_COS_LANG_MODULE['Edit'] = 'Rediger';
$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Add sub category'] = 'Legg til kategori';
$_COS_LANG_MODULE['Sub category has been added'] = 'Sub kategori er lagt';
$_COS_LANG_MODULE['Category has sub categories'] = 'Kategorien har underkategorier';
$_COS_LANG_MODULE['Category has been deleted'] = 'Kategorien har blitt slettet';
$_COS_LANG_MODULE['Category has been updated'] = 'Kategorien har blitt oppdatert';
