<?php

$_COS_LANG_MODULE['Add category'] = 'Lisää luokka';
$_COS_LANG_MODULE['Title'] = 'Otsikko';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakti';
$_COS_LANG_MODULE['Description'] = 'Kuvaus';
$_COS_LANG_MODULE['Add'] = 'Lisätä';
$_COS_LANG_MODULE['Delete category'] = 'Selkeällä luokat';
$_COS_LANG_MODULE['Edit category'] = 'Luokan muokkaus';
$_COS_LANG_MODULE['Send'] = 'Lähettää';
$_COS_LANG_MODULE['Category has been added'] = 'Kohdat on lisätty';
$_COS_LANG_MODULE['Edit'] = 'Muokata';
$_COS_LANG_MODULE['Delete'] = 'Poistaa';
$_COS_LANG_MODULE['Add sub category'] = 'Lisää luokka';
$_COS_LANG_MODULE['Sub category has been added'] = 'Ala luokka on lisätty';
$_COS_LANG_MODULE['Category has sub categories'] = 'Luokka on alaluokat';
$_COS_LANG_MODULE['Category has been deleted'] = 'Luokka on poistettu';
$_COS_LANG_MODULE['Category has been updated'] = 'Luokka on päivitetty';
