<?php

$_COS_LANG_MODULE['Add category'] = 'Lägg till kategori';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Description'] = 'Beskrivning';
$_COS_LANG_MODULE['Add'] = 'Lägg';
$_COS_LANG_MODULE['Delete category'] = 'Ta bort kategori';
$_COS_LANG_MODULE['Edit category'] = 'Redigera kategori';
$_COS_LANG_MODULE['Send'] = 'Skicka';
$_COS_LANG_MODULE['Category has been added'] = 'Kategori tillkommit';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['Add sub category'] = 'Lägg underkategori';
$_COS_LANG_MODULE['Sub category has been added'] = 'Underkategori har lagts';
$_COS_LANG_MODULE['Category has sub categories'] = 'Kategori har underkategorier';
$_COS_LANG_MODULE['Category has been deleted'] = 'Kategorin har tagits bort';
$_COS_LANG_MODULE['Category has been updated'] = 'Kategorin har uppdaterats';
