<?php

// Translation of file /home/dennis/www/sweetpoints/modules/category/module.php

$_COS_LANG_MODULE['category_form_add_legend'] = 'category_form_add_legend';
$_COS_LANG_MODULE['category_form_add_title'] = 'category_form_add_title';
$_COS_LANG_MODULE['category_form_add_abstract'] = 'category_form_add_abstract';
$_COS_LANG_MODULE['category_form_add_description'] = 'category_form_add_description';
$_COS_LANG_MODULE['category_form_add_submit'] = 'category_form_add_submit';
$_COS_LANG_MODULE['category_form_delete_legend'] = 'category_form_delete_legend';
$_COS_LANG_MODULE['category_form_update_legend'] = 'category_form_update_legend';
$_COS_LANG_MODULE['category_form_title'] = 'category_form_title';
$_COS_LANG_MODULE['category_form_update_submit'] = 'category_form_update_submit';
$_COS_LANG_MODULE['category_add_title'] = 'category_add_title';
$_COS_LANG_MODULE['category_add_action'] = 'category_add_action';
$_COS_LANG_MODULE['category_add_sub'] = 'category_add_sub';
$_COS_LANG_MODULE['category_add_sub_title'] = 'category_add_sub_title';
$_COS_LANG_MODULE['category_add_sub_action'] = 'category_add_sub_action';
$_COS_LANG_MODULE['category_delete_title'] = 'category_delete_title';
$_COS_LANG_MODULE['category_error_has_children'] = 'category_error_has_children';
$_COS_LANG_MODULE['category_deleted'] = 'category_deleted';
$_COS_LANG_MODULE['category_edit_title'] = 'category_edit_title';
$_COS_LANG_MODULE['category_edit_action_message'] = 'category_edit_action_message';
